# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
   environment: docs/environment.yaml

sphinx:
   configuration: docs/conf.py

submodules:
   include: all

build:
   os: "ubuntu-24.04" # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
   tools:
      python: "miniforge3-latest" # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python, miniforge3 replaces deprecated mambaforge and bundles mamba
