# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
   include: all

build:
   os: "ubuntu-lts-latest"
   tools:
      python: "3.12"
   commands:
      - pip install -r docs/requirements.txt
      - pip install -e .
      - python docs/convert_notebooks.py
      - zensical build
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - cp -r site/* $READTHEDOCS_OUTPUT/html/
