# in your terminal, run conda: conda env create -f environment.yml
name: timex
channels:
  - conda-forge
  - cmutel
  - diepers
dependencies:
  - python==3.11
  - bw_timex>=0.3.3
  # - brightway25_nosolver # uncomment for macOS ARM machines
  # - scikit-umfpack==0.3.3 # uncomment for macOS ARM machines
  # - numpy==1.24 # uncomment for macOS ARM machines
