# in your terminal, run conda: conda env create -f environment.yml
name: timex_test
channels:
  - conda-forge
  - cmutel
  - diepers
dependencies:
 - bw_timex>=0.3
 - brightway25_nosolver # uncomment for macOS ARM machines
 - scikit-umfpack # uncomment for macOS ARM machines
